// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: oneofs.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OneOf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Result:
	//
	//	*OneOf_Id
	//	*OneOf_Name
	Result isOneOf_Result `protobuf_oneof:"result"`
}

func (x *OneOf) Reset() {
	*x = OneOf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_oneofs_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OneOf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneOf) ProtoMessage() {}

func (x *OneOf) ProtoReflect() protoreflect.Message {
	mi := &file_oneofs_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneOf.ProtoReflect.Descriptor instead.
func (*OneOf) Descriptor() ([]byte, []int) {
	return file_oneofs_proto_rawDescGZIP(), []int{0}
}

func (m *OneOf) GetResult() isOneOf_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (x *OneOf) GetId() uint32 {
	if x, ok := x.GetResult().(*OneOf_Id); ok {
		return x.Id
	}
	return 0
}

func (x *OneOf) GetName() string {
	if x, ok := x.GetResult().(*OneOf_Name); ok {
		return x.Name
	}
	return ""
}

type isOneOf_Result interface {
	isOneOf_Result()
}

type OneOf_Id struct {
	Id uint32 `protobuf:"varint,1,opt,name=id,proto3,oneof"`
}

type OneOf_Name struct {
	Name string `protobuf:"bytes,2,opt,name=name,proto3,oneof"`
}

func (*OneOf_Id) isOneOf_Result() {}

func (*OneOf_Name) isOneOf_Result() {}

var File_oneofs_proto protoreflect.FileDescriptor

var file_oneofs_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x6f, 0x6e, 0x65, 0x6f, 0x66, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e,
	0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x6f, 0x6e, 0x65, 0x6f, 0x66, 0x73, 0x22, 0x39,
	0x0a, 0x05, 0x4f, 0x6e, 0x65, 0x4f, 0x66, 0x12, 0x10, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x48, 0x00, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x42,
	0x08, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x42, 0x1b, 0x5a, 0x19, 0x63, 0x6f, 0x75,
	0x72, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x67, 0x6f, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_oneofs_proto_rawDescOnce sync.Once
	file_oneofs_proto_rawDescData = file_oneofs_proto_rawDesc
)

func file_oneofs_proto_rawDescGZIP() []byte {
	file_oneofs_proto_rawDescOnce.Do(func() {
		file_oneofs_proto_rawDescData = protoimpl.X.CompressGZIP(file_oneofs_proto_rawDescData)
	})
	return file_oneofs_proto_rawDescData
}

var file_oneofs_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_oneofs_proto_goTypes = []interface{}{
	(*OneOf)(nil), // 0: example.oneofs.OneOf
}
var file_oneofs_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_oneofs_proto_init() }
func file_oneofs_proto_init() {
	if File_oneofs_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_oneofs_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OneOf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_oneofs_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*OneOf_Id)(nil),
		(*OneOf_Name)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_oneofs_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_oneofs_proto_goTypes,
		DependencyIndexes: file_oneofs_proto_depIdxs,
		MessageInfos:      file_oneofs_proto_msgTypes,
	}.Build()
	File_oneofs_proto = out.File
	file_oneofs_proto_rawDesc = nil
	file_oneofs_proto_goTypes = nil
	file_oneofs_proto_depIdxs = nil
}
